= Comandos de filtrado

En linux trabajamos mucho con archivos de texto, debido a esto tenemos
a nuestra disposición una variedad de comandos que ayudan a filtrar la
información que se encuentra en este tipo de archivos.


== ¿Cómo filtrar información?
*grep* es un comando de unix que nos permite filtrar lineas de un 
archivo de texto, *grep* busca patrones de texto en cada linea y solo 
muestra las lineas en las que encuentra el patrón.

Por lo general estos patrones son cadenas de texto pero no se limitan 
solo a patrones de este tipo.

Forma de uso.
[source,shell]
grep [opciones] patron [archivo]
grep [opciones] [-e patron]... [-f archivo]... [archivo]

Algunas opciones de *grep*
[cols="1,5"]
|===
|`-i` +
`--ignore-case`| Ignora si las letras son mayúsculas o minúsculas.
|`-v` +
`--invert-`| En lugar de mostrar las lineas que coinciden los patrones, 
muestra las lineas que no coinciden.
|===

=== Práctica
Para las practicas de esta sección copia el archivo 
/tmp/material/datos/datos.csv

Filtra las lineas del archivo de datos que copiaste para que solo muestre
las lineas que contienen la palabra "Fire".

== Head y Tail
*head* y *tail* son comandos que muestran solo las primeras y las ultimas 
lineas de un archivo respectivamente.

Opción importante
[cols="1,5"]
|===
|`-n` *N* | Muestra *N* lineas.
|===

=== Práctica 
. Muestra las lineas de la 5 a la 10 del archivo de datos.
. Muestra la penúltima linea del archivo de datos.

== Cut
*cut* es un comando que se usa en archivos que contienen diferentes 
campos en cada linea, y nos permite mostrar solo los campos seleccionados,
para que *cut* funcione es necesario que los campos estén separados por 
un carácter especifico.

Opciones importantes.
[cols="1,5"]
|===
|`-d` *D* | De esta forma indicamos que *D* delimita los campos dentro del archivo.
|`-f` *F* | De esta forma indicamos cuales son los campos que queremos mostrar. *F* es una lista de números.
|===

=== Práctica
Muestra el segundo y sexto campo de las primeras 10 lineas del archivo de datos.

== Sort
*sort* ordena las lineas de un archivo, para esto podemos indicar los 
campos que se usaran para el ordenamiento y la forma en la que se ordenaran.

Opciones de *sort*.
[cols="1,4"]
|===
|`-k` *K*| *K* es la lista de campos usados en el ordenamiento.
|`-t` *T*| *T* es el separador de campos.
|`-n` | Ordena las lineas en orden numérico.
|`-r` | Usa el orden inverso.
|===

=== Práctica
Muestra la segunda columna por orden alfabético.

== Wc
*wc* cuenta lineas, palabras o caracteres dentro de un archivo.

Opciones 
[cols="1,4"]
|===
|`-c` | Muestra el total de caracteres.
|`-w` | Muestra el total de palabras.
|`-l` | Muestra el total de lineas.
|===

=== Práctica
Muestra el total de lineas dentro del archivo de datos que contienen la palabra water.
