= Redirección y Pipes

== Redirección
Cada proceso tiene al menos tres canales de comunicación.

* Entrada estándar (STDIN)
* Salida estándar (STDOUT)
* Error estándar (STDERR)

Muchos comandos de UNIX aceptan su entrada desde STDIN y escriben su 
salida a STDOUT. Esto permite enlazar comandos como si se tratara de bloques de construcción.

El shell interpreta los símbolos <, > y >> como instrucciones de redirigir 
las entradas desde algún archivo, al igual que las salidas.

Comportamiento de los operadores <, >, >> y 2>
[cols="1,3"]
|===
|<| Usa el contenido de un archivo como STDIN
|>| Redirige STDOUT a un archivo, sustituye el contenido previo del archivo
|>>| Redirige STDOUT a un archivo, escribe al final del contenido previo del archivo
|2>| Redirige STDERR a un archivo
|===

Uso de los operadores <, >, >>.
[source,shell]
comando < archivo-entrada
comando > archivo-salida
comando >> archivo-salida
comando 2> archivo-error

TIP: Ejercicio.
Copia el contenido del archivo */etc/passwd* al archivo */tmp/passwd* usando el comando *cat* 

TIP: Ejercicio.
Copia las primeras 15 lineas del archivo */etc/passwd* al archivo */tmp/passwd2* usando el comando *head* 

TIP: Ejercicio. 
Agrega la linea "Esto es una copia de /etc/passwd" al final del archivo */tmp/passwd* usando el comando *echo*

== Pipes
Para enviar la salida estándar de un comando como entrada estándar de otro, 
usamos el símbolo pipe (|), de esta forma se pueden enlazar tantos comandos como se desee.

Uso del operador |
[source,shell]
comando1 | comando2 | comando3

La salida del comando1 es usada como entrada para el comando2 y 
la salida del comando 2 es usada comoentrada para el comando3.

Ejemplo.
[source,shell]
head /proc/cpuinfo
head /proc/cpuinfo | tr a-z A-Z
