= Scripts

:table-caption: Tabla
:figure-caption: Figura

Un script de shell es una serie de comandos escritos en un archivo; el shell lee los comandos del archivo tal como lo haría si los escribieras en una terminal.

Los scripts de Bash comienzan con la siguiente línea, que indica que el programa `/bin/bash` debe ejecutar los comandos en el archivo de script.

----
#!/bin/bash
----

.Estructura de un script de Bash
----
#!/bin/sh

# Soy un comentario 
# Soy otro comentario 

# Instruccion 1
# Instruccion 2
...
# Instrucción n
----

[NOTE, caption=NOTA]
====
Se conoce como shebang al conjunto de caracteres #!. Con excepción del shebang en la parte superior de un script, un # al comienzo de una línea indica un comentario; es decir, el shell ignora cualquier cosa en la línea después de #.
====

Para ejecutar un script utilice el comando `bash` seguido del nombre del script:

----
bash mi_script.sh 
----

[#actividades_condicionales]
==== *Actividades*

. Ejecute el script _hello_world.sh_.


[#variables]
== Variables

En matemáticas se llama variable a cualquier símbolo que representa a cualquier valor de los comprendidos en un conjunto.

----
x = 3.141592
z = 1.618034
----

En programación una variable es un contenedor con nombre para un conjunto particular de bits o tipo de datos.


[#asignacion]
=== Asignación

Para asignar un valor a una variable, siga el formato:

----
nombre_variable=valor
----

Una variable puede contener un número, un carácter o una cadena de caracteres. Por ejemplo:

----
nombre=juan
edad=23
tipo_sangre=A
----

[NOTE, caption=NOTA]
====
En Bash no es necesario declarar una variable, solo asignarle un valor.
====


[#valor]
=== Valor

Para obtener el valor de una variable, utilice el símbolo `$` seguido del nombre de la variable:

----
$nombre_variable
----

En particular, para imprimir el valor de una variable, siga el formato:

----
echo $mi_variable
----

Por ejemplo:

----
echo $edad
23
----

[#variables_especiales]
== Variables especiales

Son variables que el shell establece internamente y que están disponibles para el usuario.

.Variables especiales del shell
[cols="^.^1,.^1", options="autowidth, header"]
|===
|Variable
|Descripción

|`$0`
|Nombre del script.

|`$n`
|Argumento `n` pasado al script.

|`$#`
|Número de argumentos pasados al script.

|`$@`
|Todos los argumentos pasados al script.
|`$$`

|ID de proceso del shell actual.

|`$?`
|Código de salida del último comando que el shell ejecutó.
|===


[#codigos_salida]
=== Códigos de salida

Cuando un programa finaliza, deja un _código de salida_, un valor numérico también conocido como _código de error_ o _valor de salida_. Cuando el código de salida es cero (0), generalmente significa que el programa se ejecutó sin problemas. Sin embargo, si el programa tiene un error, suele salir con un número distinto de 0.

[#actividades_variables]
==== *Actividades*

. Ejecute el script _special_variables.sh_.
. Imprima el código de salida del script _special_variables.sh_.


[#condicionales]
== Condicionales

Los condicionales se utilizan en los lenguajes de programación para realizar cualquier tarea de toma de decisiones.

.Estructura general de un condicional en Bash
----
if [ COMANDO_1 ]
then
   # Código
elif [ COMANDO_2 ]
then
   # Código
else
   # Código
fi
----

Las palabras _if_, _then_, _elif_, _else_ y _fi_ son palabras reservadas o palabras clave (keywords), es decir, que tiene un significado especial para el shell.

Los condicionales funcionan de la siguiente manera:

. El shell ejecuta el comando después de la palabra clave _if_ y guarda el código de salida de ese comando.
. Si el código de salida es 0, el shell ejecuta los comandos que se encuentran después de la palabra clave _then_, deteniéndose cuando llega a una palabra clave _elif_, _else_ o _fi_.
. Si el código de salida no es 0 y hay una cláusula _elif_, el shell ejecuta el comando después de la palabra clave _elif_ y guarda el código de salida de ese comando.
. Si el código de salida es 0, el shell ejecuta los comandos que se encuentran después de la palabra clave _then_, deteniéndose cuando llega a una palabra clave _else_ o _fi_.
. Si el código de salida es 0 y hay una cláusula _else_, el shell ejecuta los comandos que se encuentran despues de la palabra clave _else_.
. El condicional termina con la palabra clave _fi_.

.Operadores de comparación numérica
[cols="^.^1,.^1", options="autowidth, header"]
|===
|Operador
|Descripción

|-gt
|Es mayor que

|-lt
|Es menor que

|-ge
|Es mayor que o igual a

|-le
|Es menor que o igual a

|-eq
|Es igual a

|-ne
|No es igual a
|===

.Ejemplo de condicional
----
#!/bin/bash

mayoria_edad=18
tercera_edad=60
edad=15

if [ $edad -ge $tercera_edad ]
then
    echo "Eres un adulto mayor"                                                                                                                                                              
elif [ $edad -ge $mayoria_edad ]
then
    echo "Eres mayor de edad"
else
    echo "Eres menor de edad"
fi
----


[#operadores_logicos]
=== Operadores lógicos

[#and]
==== *AND*

El operador lógico `&&` (_and_) funciona de la siguiente forma:

----
COMANDO_1 && COMANDO_2
----

El shell ejecuta el `COMANDO_1`:

. Si su código de salida es 0, entonces el shell ejecuta el `COMANDO_2`.
. En caso contrario, el shell no ejecuta el `COMANDO_2`.

En un condicional:

. Si el código de salida del `COMANDO_1` es 0, el shell ejecuta el `COMANDO_2`, y utiliza su código de salida para la instrucción _if_.
. Si el código de salida del `COMANDO_1` es diferente de 0, el shell utiliza este código de salida para la instrucción _if_.

.Ejemplo de condicional utilizando el operador lógico &&
----
#!/bin/sh

if [ $1 -gt 1 ] && [ $1 -lt 10 ]
then
	echo "El número $1 es mayor que 1 y menor que 10"
fi
----

[#or]
==== *OR*

El operador lógico `||` (_or_) funciona de la siguiente forma:

----
	COMANDO_1 || COMANDO_2
----

El shell ejecuta el `COMANDO_1`:

. Si su código de salida es 0, el shell no ejecuta el `COMANDO_2`.
. En caso contrario, el shell ejecuta el `COMANDO_2`.

En un condicional:

. Si el código de salida del `COMANDO_1` es 0, el shell utiliza este código de salida para la instrucción _if_.
. Si el código de salida del `COMANDO_1` es diferente de 0, el shell ejecuta el `COMANDO_2`, y utiliza su código de salida para la instrucción _if_.

.Ejemplo de condicional utilizando el operador lógico ||
----
#!/bin/sh

if [ $1 -lt 10 ] || [ $1 -gt 20 ]
then
	echo "El número $1 es menor que 10 o mayor que 20"
fi
----


[#actividades_condicionales]
==== *Actividades*

. Realizar un script que determine el mayor de tres números.


[#ciclos]
== Ciclos

Un ciclo es una secuencia de comandos que se ejecutan repetidas veces, hasta alcanzar una condición determinada.

Hay dos tipos de bucles en Bash: 

* for
* while


[#for]
=== for

.Estructura básica del ciclo for en Bash
----
for VARIABLE in ELEMENTOS
do
	# Código
done
----

Las palabras _for_, _in_, _do_ y _done_ son palabras reservadas.

.Imprime los números del 1 al 5 utilizando el ciclo for 
----
#!/bin/bash

for numero in 1 2 3 4 5; do
	echo $numero
done
----


[#while]
=== while

.Estructura básica del ciclo while en Bash
----
while COMANDO
do
	# Código
done
----

Las palabras _while_, _do_ y _done_ son palabras reservadas.

.Imprime los números del 1 al 5 utilizando el ciclo while
----
#!/bin/bash

x=1

while [ $x -le 5 ]
do
	echo $x
	x=$(( $x + 1 ))
done
----
