= Comodines

:table-caption: Tabla
:figure-caption: Figura

Los comodines (también conocidos como metacaracteres) son símbolos o caracteres especiales que representan
a otros caracteres. Puede usarlos con cualquier comando, como el comando `ls` o el comando `rm`, para enumerar
o eliminar archivos que coincidan con un criterio dado

=== Descripción de metacaracteres

|===
| Metacaracter | Descripción | Ejemplo

| `*`   | Cualquier cadena, sin importar su longitud  | 12*3 coincide con 1223, 12345 y 123
| `?`   | Cualquier carácter | sept? coincide con sept y sepa.
| `[-]`   | Indica un rango de valores que se van a comparar (El rango debe estar entre paréntesis.).| [1–5][1-9][1-9] [1-9][1-9] coincide con cadenas, como por ejemplo, 12345 o 26589, pero no 67890. 
| `[...]`  | Contiene caracteres específicos y rangos de valores que deben coincidir. | [xyz] coincide con cadenas que contienen x, y o z.
| `[!..]`  | Cualquier carácter excepto los caracteres en el rango | sep[!1] coincide con sep2, sept y sepa pero no con sep1.
| `{}`     | Para hacer coincidir un grupo de patrones de nombres/comodines | touch prueba{1..3}.txt creara los archivos prueba1.txt, prueba2.txt y prueba2.txt
|===

==== Práctica

Los metacaracteres son utilizados para construir expresiones regulares. Con BASH, el propio shell expande
los comodines. Esto significa que los comandos generalmente no ven estos caracteres especiales porque BASH
ya los ha expandido antes de ejecutar el comando. Intente familiarizarse con los comodines con los siguientes ejemplos:

----
$ touch gcutError_recon-all.log s{10,1,6,8}_recon-all.log  s3-recon-all.log

$ ls
gcutError_recon-all.log  s10_recon-all.log  s1_recon-all.log
s3-recon-all.log  s6_recon-all.log  s8_recon-all.log

$ ls *recon-all.log
gcutError_recon-all.log  s10_recon-all.log  s1_recon-all.log
s6_recon-all.log      s8_recon-all.log

$ ls gcut*
gcutError_recon-all.log

$ ls s[0-9]*
s10_recon-all.log  s1_recon-all.log  s3-recon-all.log
s6_recon-all.log  s8_recon-all.log

$ ls s[0-9]_*
s1_recon-all.log  s6_recon-all.log  s8_recon-all.log

$ ls s[0-9][0-9]_*
s10_recon-all.log

$ ls [a-z][0-9][0-9]???con-all.log
s10_recon-all.log

$ ls s?_recon-all.log
s1_recon-all.log  s6_recon-all.log  s8_recon-all.log

$ touch subject_{1..5}.dat

$ ls
gcutError_recon-all.log  s1_recon-all.log  s6_recon-all.log
s10_recon-all.log        s3-recon-all.log  s8_recon-all.log
subject_1.dat  subject_3.dat  subject_5.dat
subject_2.dat  subject_4.dat
----

==== Ejercicios

. Encuentre un patrón de búsqueda que devuelva todos los archivos que terminan en `.txt`
. Encuentre un patrón de búsqueda que devuelva todos los archivos que comiencen con `s` y terminen en `.log`
. Encuentre un patrón de búsqueda que devuelva todos los archivos que comiencen con `s` seguidos de dos dígitos
. Encuentre un patrón de búsqueda que devuelva todos los archivos que comiencen con `s` seguidos de un *solo* dígito
. Ejecute un comando que elimine todos los archivos que terminen con `.dat`


.Respuestas
[%collapsible]
====
. ls *.txt
. ls s*.log
. ls s[0-9][0-9]*
. ls s[0-9][!0-9]*
. rm *.dat
====
