= Comodines

:table-caption: Tabla
:figure-caption: Figura

Los comodines (también conocidos como metacaracteres) son símbolos o caracteres especiales que representan
a otros caracteres. Puede usarlos con cualquier comando, como el comando `ls` o el comando `rm`, para enumerar
o eliminar archivos que coincidan con un criterio dado

== Descripción de metacaracteres

|===
| Metacaracter | Descripción | Ejemplo

| `*`   | Cualquier cadena, sin importar su longitud  | 12*3 coincide con 1223, 12345 y 123
| `?`   | Cualquier carácter | sept? coincide con sept y sepa.
| `[-]`   | Indica un rango de valores que se van a comparar (El rango debe estar entre paréntesis.).| [1–5][1-9][1-9] [1-9][1-9] coincide con cadenas, como por ejemplo, 12345 o 26589, pero no 67890. 
| `[...]`  | Contiene caracteres específicos y rangos de valores que deben coincidir. | [xyz] coincide con cadenas que contienen x, y o z.
| `[!..]`  | Cualquier carácter excepto los caracteres en el rango | sep[!1] coincide con sep2, sept y sepa pero no con sep1.
| `{}`     | Para hacer coincidir un grupo de patrones de nombres/comodines | touch prueba{1..3}.txt creara los archivos prueba1.txt, prueba2.txt y prueba2.txt
|===

== Práctica

Los metacaracteres son utilizados para construir expresiones regulares. Con BASH, el propio shell expande
los comodines. Esto significa que los comandos generalmente no ven estos caracteres especiales porque BASH
ya los ha expandido antes de ejecutar el comando. Intente familiarizarse con los comodines con los siguientes ejemplos:

----
$ touch gcutError_recon-all.log s{10,1,6,8}_recon-all.log  s3-recon-all.log

$ ls
gcutError_recon-all.log  s10_recon-all.log  s1_recon-all.log
s3-recon-all.log  s6_recon-all.log  s8_recon-all.log

$ ls *recon-all.log
gcutError_recon-all.log  s10_recon-all.log  s1_recon-all.log
s6_recon-all.log      s8_recon-all.log

$ ls gcut*
gcutError_recon-all.log

$ ls s[0-9]*
s10_recon-all.log  s1_recon-all.log  s3-recon-all.log
s6_recon-all.log  s8_recon-all.log

$ ls s[0-9]_*
s1_recon-all.log  s6_recon-all.log  s8_recon-all.log

$ ls s[0-9][0-9]_*
s10_recon-all.log

$ ls [a-z][0-9][0-9]???con-all.log
s10_recon-all.log

$ ls s?_recon-all.log
s1_recon-all.log  s6_recon-all.log  s8_recon-all.log

$ touch subject_{1..5}.dat

$ ls
gcutError_recon-all.log  s1_recon-all.log  s6_recon-all.log
s10_recon-all.log        s3-recon-all.log  s8_recon-all.log
subject_1.dat  subject_3.dat  subject_5.dat
subject_2.dat  subject_4.dat
----

== Ejercicios

. Encuentre un patrón de búsqueda que devuelva todos los archivos que terminan en `.txt`
. Encuentre un patrón de búsqueda que devuelva todos los archivos que comiencen con `s` y terminen en `.log`
. Encuentre un patrón de búsqueda que devuelva todos los archivos que comiencen con `s` seguidos de dos dígitos
. Encuentre un patrón de búsqueda que devuelva todos los archivos que comiencen con `s` seguidos de un *solo* dígito
. Ejecute un comando que elimine todos los archivos que terminen con `.dat`


.Respuestas
[%collapsible]
====
. ls *.txt
. ls s*.log
. ls s[0-9][0-9]*
. ls s[0-9][!0-9]*
. rm *.dat
====

= Actividades del día.

:table-caption: Tabla
:figure-caption: Figura

* Probamos el comando *echo* con el mensaje _hola mundo_.

----
$ echo hola mundo
hola mundo
----

* Revisamos la ruta recorrida (en dónde estamos) usando el comando *pwd*.

----
$ pwd 
/home/usuario
----

* Copiamos el material necesario para el curso con:

----
$ cp -r /tmp/.../dia_1 .
----

* Con *ls* visualizamos los archivos que hay.

----
$ ls 
dia_1
----

----
$ ls dia_1
animales  comodines
----

* Usamos *cd* y ls para explorar los directorios.

* Dentro de _animales/salvajes_ creamos un directorio con cualquier nombre de ecosistema.

* Intentamos crear el directorio _dia_1/plantas/selva_. Notamos que no se puede porque no existe el directorio intermedio plantas.

* Investigando en el manual observamos que es necesario usar la opción *-p* junto con *mkdir*, esto estando en el directorio dia_1 aunque podemos hacerlo desde cualquier lugar.

----
$ pwd
/home/usuario/dia_1

$ mkdir -p  plantas/selva
----

* Probamos el comando *touch* para crear algún animal domestico dentro del directorio _/home/usuario/dia_1/animales/domesticos_

* Copiamos al _ajolote_ y creamos _ajolote2_ y _ajolote3_.

* Para copiar un directorio con archivos, necesitamos hacer una copia recurrente. Investigamos en el manual de *cp* cómo hacerlo.

* Usando *cp -r* hacemos una "copia de seguridad" de _animales_ con el nombre que queramos.

* Existen animales dentro de hábitats erróneos, los movemos de lugar utilizando *mv*.

* Algunos animales "evolucionaron", copiamos al _lobo_ del directorio _tundra_ al directorio _domesticos_ y le cambiamos el nombre a _perro_.

* En algunos directorios hay animales extintos. Los eliminamos con *rm*.

* El directorio _pantano_ está *vacío*, por lo que podemos eliminarlo con *rmdir*.

* ¡Ocurrio una catástrofeo! El hábitad _pangea_ y todos sus animales murieror. Lo eliminamos todo con *rm -r*.

* Algunos archivos tienen información acerca de los animales. ¿Cuáles son? Usamos *ls -l* para ver el tamaño de los directorios y así deducir cuáles tienen texto. ¿Qué tienen dentro estos archivos? Usamos *cat* para visualizar en pantalla su contenido.

* Utilizando el comando *find* buscamos a los animales _perico_, _cangrejo_, _tortuga_, _tiburon_, _jaguar_, _pinguino_ y _calamar_.
