= Actividades del día.

:table-caption: Tabla
:figure-caption: Figura

* Probamos el comando *echo* con el mensaje _hola mundo_.

----
$ echo hola mundo
hola mundo
----

* Revisamos la ruta recorrida (en dónde estamos) usando el comando *pwd*.

----
$ pwd 
/home/usuario
----

* Copiamos el material necesario para el curso con:

----
$ cp -r /tmp/.../dia_1 .
----

* Con *ls* visualizamos los archivos que hay.

----
$ ls 
dia_1
----

----
$ ls dia_1
animales  comodines
----

* Usamos *cd* y ls para explorar los directorios.

* Dentro de _animales/salvajes_ creamos un directorio con cualquier nombre de ecosistema.

* Intentamos crear el directorio _dia_1/plantas/selva_. Notamos que no se puede porque no existe el directorio intermedio plantas.

* Investigando en el manual observamos que es necesario usar la opción *-p* junto con *mkdir*, esto estando en el directorio dia_1 aunque podemos hacerlo desde cualquier lugar.

----
$ pwd
/home/usuario/dia_1

$ mkdir -p  plantas/selva
----

* Probamos el comando *touch* para crear algún animal domestico dentro del directorio _/home/usuario/dia_1/animales/domesticos_

* Copiamos al _ajolote_ y creamos _ajolote2_ y _ajolote3_.

* Para copiar un directorio con archivos, necesitamos hacer una copia recurrente. Investigamos en el manual de *cp* cómo hacerlo.

* Usando *cp -r* hacemos una "copia de seguridad" de _animales_ con el nombre que queramos.

* Existen animales dentro de hábitats erróneos, los movemos de lugar utilizando *mv*.

* Algunos animales "evolucionaron", copiamos al _lobo_ del directorio _tundra_ al directorio _domesticos_ y le cambiamos el nombre a _perro_.

* En algunos directorios hay animales extintos. Los eliminamos con *rm*.

* El directorio _pantano_ está *vacío*, por lo que podemos eliminarlo con *rmdir*.

* ¡Ocurrio una catástrofeo! El hábitad _pangea_ y todos sus animales murieror. Lo eliminamos todo con *rm -r*.

* Algunos archivos tienen información acerca de los animales. ¿Cuáles son? Usamos *ls -l* para ver el tamaño de los directorios y así deducir cuáles tienen texto. ¿Qué tienen dentro estos archivos? Usamos *cat* para visualizar en pantalla su contenido.

* Utilizando el comando *find* buscamos a los animales _perico_, _cangrejo_, _tortuga_, _tiburon_, _jaguar_, _pinguino_ y _calamar_.
